apiVersion: codefresh.io/v1beta2
kind: Product
metadata:
  name: trio
spec:
  promotionTemplate:
    versionSource:
      file: values.yaml
      jsonPath: $.sub2.sub3.version3
    promotion:
      values.yaml:
        jsonPaths:
          - $.*.*.tag
          - $.sub2.sub3.version3
  concurrency: queue
