apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: csdp
  labels:
    codefresh.io/entity: runtime
    codefresh.io/internal: 'true'
spec:
  project: default
  source:
    repoURL: https://github.com/lrochette/ISC.git
    targetRevision: HEAD
    path: resources/csdp/chart
    helm:
      releaseName: csdp
  destination:
    namespace: csdp
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
