apiVersion: codefresh.io/v1beta1
kind: PromotionFlow
metadata:
  name: dev-to-prod
  annotations:
    description: For testing jira
    version: 0.0.1
spec:
  triggerEnvironment: dev
  steps:
    - environment: prod
      dependsOn:
        - dev
      policy:
        action: pr
