# DO NOT REMOVE the following attributes:
# annotations.codefresh.io/workflow-origin (identifies type of Workflow Template as Promotion Workflow)
# annotations.version (identifies version of Promotion Workflow used)
# annotations.description (identifies intended use of the Promotion Workflow)

apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: service-now-close-success
  annotations:
    codefresh.io/workflow-origin: promotion
    codefresh.io/promotion-stage: post-action
    version: 0.0.1
    description: 'promotion workflow template'

spec:
  serviceAccountName: cf-default-promotion-workflows-sa
  entrypoint: main
  arguments:
    parameters:
    - name: PRODUCT_NAME
    - name: CR_SYSID
  templates:
  - name: main
    dag:
      tasks:
        - name: close-sn-cr
          templateRef:
            name: argo-hub.servicenow.1.4.0
            template: closecr
          arguments:
            parameters:
            - name: SN_INSTANCE
              value: 'https://dev286098.service-now.com'
            - name: SN_AUTH
              value: "sn-auth"
            - name: CR_DATA
              value: '{"work_notes":"this is a message for the work notes"}'
            - name: CR_SYSID
              value: '{{ workflow.parameters.CR_SYSID }}'
            - name: LOG_LEVEL
              value: info
            - name: CR_CLOSE_CODE
              value: "successful"
            - name: CR_CLOSE_NOTES
              value: "App {{ workflow.parameters.PRODUCT_NAME }} installed with success so we close the Change Request."
