apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: null
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  labels:
    codefresh.io/entity: internal-config
    codefresh.io/internal: "true"
  name: in-cluster
spec:
  destination:
    namespace: obsolete
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      include: '{control-planes/*.yaml,obsolete/default-git-source.yaml,all-runtimes-all-clusters/*.yaml,runtimes/obsolete/**/*.yaml,obsolete/marketplace-git-source.yaml,control-planes/**/*.yaml,obsolete/codefresh-config-reader.yaml,all-runtimes-all-clusters/**/*.yaml,runtimes/obsolete/*.yaml}'
      jsonnet: {}
      recurse: true
    path: resources
    repoURL: https://github.com/lrochette/ISC.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
    - allowEmpty=true