apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    codefresh.io/entity: internal-config
    codefresh.io/internal: 'true'
  name: main
spec:
  destination:
    namespace: default
    server: https://B8D1E54206772D2AC7CC62D992BA3642.gr7.us-east-1.eks.amazonaws.com
  project: default
  source:
    directory:
      include: >-
        {all-runtimes-all-clusters/*.yaml,all-runtimes-all-clusters/**/*.yaml,runtimes/csdp/*.yaml,runtimes/csdp/**/*.yaml,csdp-managed-cluster-main-cm.yaml}
      recurse: true
    path: resources
    repoURL: https://github.com/lrochette/ISC.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - allowEmpty=true
