apiVersion: v2
appVersion: 0.1.29
description: Codefresh gitops runtime umbrella chart
name: codefresh-gitops-runtime
version: 0.2.6-alpha
dependencies:
  - name: gitops-runtime
    repository: https://chartmuseum.codefresh.io/gitops-runtime
    version: 0.2.6-alpha
