gitops-runtime:
  global:
    codefresh:
      accountId: 600edc0bdffeb2bc4981d15a
      userToken:
        secretKeyRef:
          name: codefresh-user-token
          key: token
    runtime:
      ingress:
        className: nginx
        enabled: true
        hosts:
          - lrcsdp.support.cf-cd.com
      name: csdp
  installer:
    skipValidation: true
