apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: codefresh-config-reader
  namespace: obsolete
rules:
- apiGroups:
  - ""
  resourceNames:
  - codefresh-cm
  - codefresh-token
  resources:
  - configmaps
  - secrets
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: codefresh-config-reader
  namespace: obsolete
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: codefresh-config-reader
subjects:
- kind: ServiceAccount
  name: default
  namespace: obsolete
