apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations: 
    argocd.argoproj.io/sync-wave: '0'
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/managed-by: argocd-autopilot
    app.kubernetes.io/name: 'default-git-source'
    codefresh.io/entity: 'git-source'
    codefresh.io/internal: 'false'
  name: 'obsolete-default-git-source'
spec:
  destination:
    namespace: 'obsolete'
    server: 'https://kubernetes.default.svc'
  ignoreDifferences:
  - group: argoproj.io
    jsonPointers:
    - /status
    kind: Application
  project: default
  source:
    path: 'resources_obsolete'
    repoURL: 'https://github.com/lrochette/obsolete_git-source.git'
    targetRevision: ''
    directory:
      exclude: ''
      include: ''
      recurse: true
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
