apiVersion: codefresh.io/v1beta1
kind: RestrictedGitSource
metadata:
  name: ta-gs
spec:
  source:
    repoURL: https://github.com/lrochette/ta-autopilot.git
    path: gs
    targetRevision: main
    directory:
      include: '*'
      exclude: ''
      recurse: true
  destinations:
  - server: 'https://kubernetes.default.svc'
    name: 'in-cluster'
    namespace: 'dev'
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
  sourceRepos:
  - '*'
  sourceNamespace: 'cf-ta'
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
    - allowEmpty=true
    - CreateNamespace=true
