gitops-runtime:
  app-proxy:
    config:
      cors: >-
        http://local.codefresh.io,https://g.codefresh.io,https://sandbox-1.codefresh.io,https://sandbox-2.codefresh.io,https://sandbox-3.codefresh.io
    env:
      HELM_REPOSITORY: oci://quay.io/codefresh/dev/gitops-runtime
    image:
      repository: quay.io/codefresh/cap-app-proxy
      tag: 1.3322.0
  argo-cd:
    enabled: false
  gitops-operator:
    argoCdNotifications:
      image:
        repository: quay.io/codefresh/argocd
        tag: v2.13.3-2025.2.12-7bfd6c858
      imageOverride: true
    enabled: true
  global:
    codefresh:
      accountId: 600edc0bdffeb2bc4981d15a
      userToken:
        secretKeyRef:
          name: codefresh-user-token
          key: token
    external-argo-cd:
      passwordSecretKeyRef:
        key: password
        name: argocd-initial-admin-secret
      redis:
        port: 6379
        svc: argocd-redis
      repoServer:
        port: 8081
        svc: argocd-repo-server
      server:
        port: 80
        protocol: http
        svc: argocd-server
      username: admin
    runtime:
      ingress:
        className: nginx-internal
        enabled: true
        hosts:
          - ta.cs-sandbox.cf-infra.com
        skipValidation: true
      isConfigurationRuntime: false
      name: ta
  installer:
    skipValidation: true
