gitops-runtime:
  argo-cd:
    enabled: false
  global:
    codefresh:
      accountId: 600edc0bdffeb2bc4981d15a
      userToken:
        secretKeyRef:
          name: codefresh-user-token
          key: token
    runtime:
      name: cgc
