gitops-runtime:
  argo-cd:
    enabled: false
  global:
    codefresh:
      accountId: 600edc0bdffeb2bc4981d15a
      userToken:
        secretKeyRef:
          name: codefresh-user-token
          key: token
    runtime:
      name: cgc
      isConfigurationRuntime: false
      ingress:
        skipValidation: true
        className: nginx-internal
        enabled: true
        hosts:
          - cgc.cs-sandbox.cf-infra.com
    external-argo-cd:
      server:
        protocol: http

  app-proxy:
    env:
      HELM_REPOSITORY: oci://quay.io/codefresh/dev/gitops-runtime
      GRAPHQL_INTROSPECTION: "true"

    config:
      cors: 'http://local.codefresh.io,https://g.codefresh.io,https://sandbox-1.codefresh.io,https://sandbox-2.codefresh.io,https://sandbox-3.codefresh.io'
      logLevel: trace
      graphqlPlayground: "true"
